apiVersion: v1
kind: Template
labels:
  template: silver-jenkins
metadata:
  annotations:
    description: This template will rebuild and update the existing jenkins image stream
    iconClass: icon-shadowman
    openshift.io/display-name: jenkins Silver Image
    tags: silver,jenkins
  creationTimestamp: null
  name: jenkins-silver
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the jenkins application image
    name: jenkins
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the jenkins silver image
    name: jenkins-silver
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jenkins:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: "ImageStreamTag"
          name: "jenkins:latest"
          namespace: ${NAMESPACE}
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
parameters:
- description: The OpenShift Namespace where the ImageStreams reside.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: openshift
- description: The URL of the repository with the silver Dockerfile.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/kevensen/silver.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: jenkins
- description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
